### ISSUE TITLE
collective_write() needs 3 but gives 4

### ISSUE THREAD

**Issue by Eusrace** [jchelly/LightconeIO#5]
Just discover another small bug when writing output files... 

Traceback (most recent call last):
  File "/cosma7/data/dp004/dc-chen3/bin/smooth_lc.py", line 35, in <module>
    L1000N1800_HYDRO_FIDUCIAL_smoothed_gas_mass()
  File "/cosma7/data/dp004/dc-chen3/bin/smooth_lc.py", line 32, in L1000N1800_HYDRO_FIDUCIAL_smoothed_gas_mass
    phdf5.collective_write(outfile, dataset_name, map_data, comm)
TypeError: collective_write() takes 3 positional arguments but 4 were given

**Comment by jchelly** [comment]
I think that might be due to a change I made in the virgo module, which provides the collective_write function. I'll check that now.

**Comment by Eusrace** [comment]
Yes, after I update the virgo module it fixed, thanks a lot!
